= FACE DETECTOR API

The Face Detector API is an application that use the 'face-recognition' library and the algorithm of HaarCascade from OpenCV library.

== GETTING STARTED

1- Clone the repository or download the project files

[source]
git clone https://github.com/nahueltabasso/face-detector.git

2- Make sure you have python version 3.10.10 installed

3- Install the dependencies using the pip package manager

[source]
pip install -r requirements.txt

== USE
1- Save the images that you need to process in the follow directory
----
./data/
----

2- Modify the paths of the images in the notebooks by the paths of the images you want to process

3- Execute the notebooks

== API COMMENTS

To consume the APIs REST of this project you need to 

1- Start the server
[source]
uvicorn main:app --host 0.0.0.0 --port 8000

2- Make a request HTTP POST similar to this example with curl or Postman or other http client

[source]
curl -X POST \
  -H "Content-Type: multipart/form-data" \
  -H "api_key: your_api_key" \
  -F "image=@path_to_image.jpg" \
  http://localhost:8000/faceDetectAPI/detect_face

Make sure to replace "your_api_key" by the real value of this header and replace the "@path_to_image.jpg" by your image

The response of this api are similar to:
[source, json]
{
  "status": 200,
  "detected_face": true,
  "bbox_faces": [
    [
      163,
      384,
      225,
      322
    ],
    [
      205,
      475,
      257,
      423
    ]
  ],
  "number_of_detected_faces": 2
}

== CONTRIBUTIONS
All contributions are welcome. If somebody has a new idea or a form to improve this, please crear a issue to work.

== LICENSE
This project was under https://opensource.org/license/mit/[MIT LICENSE] license.

== CONTACT
If you have some question about this you can contac me to my email nahueltabasso@gmail.com
